#version: '3.8'
services:
  clickhouse-node:
    image: bitnami/clickhouse-server:24.8
    container_name: clickhouse-node
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./node/configs/config.xml:/bitnami/clickhouse/etc/conf.d/config.xml:ro
      - ./node/configs/default_users.xml:/bitnami/clickhouse/etc/users.d/default_users.xml:ro
      - clickhouse_data:/bitnami/clickhouse
      - clickhouse_logs:/opt/bitnami/clickhouse/logs
    networks:
      - clickhouse_network
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local

networks:
  clickhouse_network:
    driver: bridge